// Auto-generated from kz_en_ru_flashcards.csv
const WORDS = [
  {kz:"мен",en:"I",ru:"я",pos:"pronoun"},
  {kz:"сен",en:"you (informal)",ru:"ты",pos:"pronoun"},
  {kz:"ол",en:"he/she/it",ru:"он/она/оно",pos:"pronoun"},
  {kz:"біз",en:"we",ru:"мы",pos:"pronoun"},
  {kz:"сіз",en:"you (formal)",ru:"Вы",pos:"pronoun"},
  {kz:"олар",en:"they",ru:"они",pos:"pronoun"},
  {kz:"менің",en:"my",ru:"мой",pos:"pronoun"},
  {kz:"сенің",en:"your",ru:"твой",pos:"pronoun"},
  {kz:"оның",en:"his/her/its",ru:"его/её",pos:"pronoun"},
  {kz:"біздің",en:"our",ru:"наш",pos:"pronoun"},
  {kz:"сіздің",en:"your (formal)",ru:"ваш",pos:"pronoun"},
  {kz:"олардың",en:"their",ru:"их",pos:"pronoun"},
  {kz:"бұл",en:"this",ru:"это",pos:"pronoun"},
  {kz:"бұлар",en:"these",ru:"эти",pos:"pronoun"},
  {kz:"сол",en:"that",ru:"тот",pos:"pronoun"},
  {kz:"олар",en:"those",ru:"те",pos:"pronoun"},
  {kz:"не",en:"what",ru:"что",pos:"pronoun"},
  {kz:"кім",en:"who",ru:"кто",pos:"pronoun"},
  {kz:"қайда",en:"where",ru:"где",pos:"adverb"},
  {kz:"қашан",en:"when",ru:"когда",pos:"adverb"},
  {kz:"қалай",en:"how",ru:"как",pos:"adverb"},
  {kz:"неге",en:"why",ru:"почему",pos:"adverb"},
  {kz:"қанша",en:"how much/many",ru:"сколько",pos:"adverb"},
  {kz:"мен",en:"me",ru:"меня",pos:"pronoun"},
  {kz:"сені",en:"you",ru:"тебя",pos:"pronoun"},
  {kz:"оны",en:"him/her/it",ru:"его/её",pos:"pronoun"},
  {kz:"бізді",en:"us",ru:"нас",pos:"pronoun"},
  {kz:"сізді",en:"you (formal)",ru:"вас",pos:"pronoun"},
  {kz:"оларды",en:"them",ru:"их",pos:"pronoun"},
  {kz:"менде",en:"at me",ru:"у меня",pos:"pronoun"},
  {kz:"сенде",en:"at you",ru:"у тебя",pos:"pronoun"},
  {kz:"онда",en:"at him/her",ru:"у него/неё",pos:"pronoun"},
  {kz:"бізде",en:"at us",ru:"у нас",pos:"pronoun"},
  {kz:"сізде",en:"at you (formal)",ru:"у вас",pos:"pronoun"},
  {kz:"оларда",en:"at them",ru:"у них",pos:"pronoun"},
  {kz:"менен",en:"from me",ru:"от меня",pos:"pronoun"},
  {kz:"сенен",en:"from you",ru:"от тебя",pos:"pronoun"},
  {kz:"одан",en:"from him/her",ru:"от него/неё",pos:"pronoun"},
  {kz:"бізден",en:"from us",ru:"от нас",pos:"pronoun"},
  {kz:"сізден",en:"from you (formal)",ru:"от вас",pos:"pronoun"},
  {kz:"олардан",en:"from them",ru:"от них",pos:"pronoun"},
  {kz:"мені",en:"me (accusative)",ru:"меня (винительный)",pos:"pronoun"},
  {kz:"сені",en:"you (accusative)",ru:"тебя (винительный)",pos:"pronoun"},
  {kz:"оны",en:"him/her/it (accusative)",ru:"его/её (винительный)",pos:"pronoun"},
  {kz:"күн",en:"day",ru:"день",pos:"noun"},
  {kz:"түн",en:"night",ru:"ночь",pos:"noun"},
  {kz:"су",en:"water",ru:"вода",pos:"noun"},
  {kz:"от",en:"fire",ru:"огонь",pos:"noun"},
  {kz:"жер",en:"earth/ground",ru:"земля",pos:"noun"},
  {kz:"аспан",en:"sky",ru:"небо",pos:"noun"},
  {kz:"жыл",en:"year",ru:"год",pos:"noun"},
  {kz:"ай",en:"month/moon",ru:"месяц",pos:"noun"},
  {kz:"күн",en:"sun",ru:"солнце",pos:"noun"},
  {kz:"жұлдыз",en:"star",ru:"звезда",pos:"noun"},
  {kz:"құс",en:"bird",ru:"птица",pos:"noun"},
  {kz:"балық",en:"fish",ru:"рыба",pos:"noun"},
  {kz:"ит",en:"dog",ru:"собака",pos:"noun"},
  {kz:"мысық",en:"cat",ru:"кот",pos:"noun"},
  {kz:"ат",en:"horse",ru:"лошадь",pos:"noun"},
  {kz:"сиыр",en:"cow",ru:"корова",pos:"noun"},
  {kz:"қой",en:"sheep",ru:"овца",pos:"noun"},
  {kz:"ешкі",en:"goat",ru:"коза",pos:"noun"},
  {kz:"шошқа",en:"pig",ru:"свинья",pos:"noun"},
  {kz:"түйе",en:"camel",ru:"верблюд",pos:"noun"},
  {kz:"адам",en:"person",ru:"человек",pos:"noun"},
  {kz:"ер",en:"man",ru:"мужчина",pos:"noun"},
  {kz:"әйел",en:"woman",ru:"женщина",pos:"noun"},
  {kz:"бала",en:"child",ru:"ребёнок",pos:"noun"},
  {kz:"жігіт",en:"young man",ru:"молодой человек",pos:"noun"},
  {kz:"қыз",en:"girl",ru:"девушка",pos:"noun"},
  {kz:"ата",en:"grandfather",ru:"дедушка",pos:"noun"},
  {kz:"ана",en:"mother",ru:"мать",pos:"noun"},
  {kz:"әке",en:"father",ru:"отец",pos:"noun"},
  {kz:"бала",en:"son/daughter",ru:"сын/дочь",pos:"noun"},
  {kz:"сіңлі",en:"sister (younger)",ru:"младшая сестра",pos:"noun"},
  {kz:"аға",en:"older brother",ru:"старший брат",pos:"noun"},
  {kz:"жені",en:"younger sibling",ru:"младший брат/сестра",pos:"noun"},
  {kz:"дос",en:"friend",ru:"друг",pos:"noun"},
  {kz:"жаман",en:"bad",ru:"плохой",pos:"adjective"},
  {kz:"жақсы",en:"good",ru:"хороший",pos:"adjective"},
  {kz:"үлкен",en:"big",ru:"большой",pos:"adjective"},
  {kz:"кіші",en:"small/little",ru:"маленький",pos:"adjective"},
  {kz:"биік",en:"high",ru:"высокий",pos:"adjective"},
  {kz:"төмен",en:"low",ru:"низкий",pos:"adjective"},
  {kz:"терең",en:"deep",ru:"глубокий",pos:"adjective"},
  {kz:"жылдам",en:"fast",ru:"быстрый",pos:"adjective"},
  {kz:"баяу",en:"slow",ru:"медленный",pos:"adjective"},
  {kz:"жаңа",en:"new",ru:"новый",pos:"adjective"},
  {kz:"ескі",en:"old",ru:"старый",pos:"adjective"},
  {kz:"әдемі",en:"beautiful",ru:"красивый",pos:"adjective"},
  {kz:"сұлу",en:"beautiful (of person)",ru:"красивый (о человеке)",pos:"adjective"},
  {kz:"қатал",en:"harsh",ru:"суровый",pos:"adjective"},
  {kz:"жұмсақ",en:"soft",ru:"мягкий",pos:"adjective"},
  {kz:"қатты",en:"hard",ru:"твёрдый",pos:"adjective"},
  {kz:"ылғал",en:"wet",ru:"влажный",pos:"adjective"},
  {kz:"құрғақ",en:"dry",ru:"сухой",pos:"adjective"},
  {kz:"жылы",en:"warm",ru:"тёплый",pos:"adjective"},
  {kz:"суық",en:"cold",ru:"холодный",pos:"adjective"},
  {kz:"жеңіл",en:"easy",ru:"лёгкий",pos:"adjective"},
  {kz:"ауыр",en:"heavy",ru:"тяжёлый",pos:"adjective"},
  {kz:"аш",en:"hungry",ru:"голодный",pos:"adjective"},
  {kz:"шөл",en:"thirsty",ru:"жаждущий",pos:"adjective"},
  {kz:"шаршаған",en:"tired",ru:"уставший",pos:"adjective"},
  {kz:"ұйықтап жатқан",en:"sleepy",ru:"сонный",pos:"adjective"},
  {kz:"демалу",en:"to rest",ru:"отдыхать",pos:"verb"},
  {kz:"ішу",en:"to drink",ru:"пить",pos:"verb"},
  {kz:"жеу",en:"to eat",ru:"есть",pos:"verb"},
  {kz:"бару",en:"to go",ru:"идти",pos:"verb"},
  {kz:"келу",en:"to come",ru:"приходить",pos:"verb"},
  {kz:"кетелу",en:"to leave",ru:"уходить",pos:"verb"},
  {kz:"тұру",en:"to stand",ru:"стоять",pos:"verb"},
  {kz:"отыру",en:"to sit",ru:"сидеть",pos:"verb"},
  {kz:"жату",en:"to lie",ru:"лежать",pos:"verb"},
  {kz:"жазу",en:"to write",ru:"писать",pos:"verb"},
  {kz:"оқу",en:"to read",ru:"читать",pos:"verb"},
  {kz:"сөйлеу",en:"to speak",ru:"говорить",pos:"verb"},
  {kz:"тыңдау",en:"to listen",ru:"слушать",pos:"verb"},
  {kz:"көру",en:"to see",ru:"видеть",pos:"verb"},
  {kz:"білу",en:"to know",ru:"знать",pos:"verb"},
  {kz:"түсінбеу",en:"to not understand",ru:"не понимать",pos:"verb"},
  {kz:"сұрау",en:"to ask",ru:"спрашивать",pos:"verb"},
  {kz:"жауап беру",en:"to answer",ru:"отвечать",pos:"verb"},
  {kz:"беру",en:"to give",ru:"давать",pos:"verb"},
  {kz:"алу",en:"to take",ru:"брать",pos:"verb"},
  {kz:"жасау",en:"to make/do",ru:"делать",pos:"verb"},
  {kz:"білдіру",en:"to inform",ru:"сообщать",pos:"verb"},
  {kz:"көмектесу",en:"to help",ru:"помогать",pos:"verb"},
  {kz:"үйрену",en:"to learn",ru:"учиться",pos:"verb"},
  {kz:"оқыту",en:"to teach",ru:"обучать",pos:"verb"},
  {kz:"тәрбиелеу",en:"to raise",ru:"воспитывать",pos:"verb"},
  {kz:"өмір",en:"life",ru:"жизнь",pos:"noun"},
  {kz:"өлу",en:"to die",ru:"умирать",pos:"verb"},
  {kz:"туу",en:"to be born",ru:"рождаться",pos:"verb"},
  {kz:"сүю",en:"to love",ru:"любить",pos:"verb"},
  {kz:"жек көру",en:"to hate",ru:"ненавидеть",pos:"verb"},
  {kz:"армандау",en:"to dream",ru:"мечтать",pos:"verb"},
  {kz:"ойлау",en:"to think",ru:"думать",pos:"verb"},
  {kz:"сезіну",en:"to feel",ru:"чувствовать",pos:"verb"},
  {kz:"күлу",en:"to laugh",ru:"смеяться",pos:"verb"},
  {kz:"жылау",en:"to cry",ru:"плакать",pos:"verb"},
  {kz:"қорқу",en:"to be afraid",ru:"бояться",pos:"verb"},
  {kz:"тсыйлау",en:"to respect",ru:"уважать",pos:"verb"},
  {kz:"сену",en:"to trust",ru:"доверять",pos:"verb"},
  {kz:"күмәндану",en:"to doubt",ru:"сомневаться",pos:"verb"},
  {kz:"бақыт",en:"happiness",ru:"счастье",pos:"noun"},
  {kz:"махаббат",en:"love",ru:"любовь",pos:"noun"},
  {kz:"жұмыс",en:"work",ru:"работа",pos:"noun"},
  {kz:"іс",en:"business/affair",ru:"дело",pos:"noun"},
  {kz:"уақыт",en:"time",ru:"время",pos:"noun"},
  {kz:"мезгіл",en:"season/period",ru:"сезон/период",pos:"noun"},
  {kz:"күн",en:"weather",ru:"погода",pos:"noun"},
  {kz:"бүгін",en:"today",ru:"сегодня",pos:"adverb"},
  {kz:"ертең",en:"tomorrow",ru:"завтра",pos:"adverb"},
  {kz:"кеше",en:"yesterday",ru:"вчера",pos:"adverb"},
  {kz:"бұрын",en:"before",ru:"раньше",pos:"adverb"},
  {kz:"кейін",en:"after",ru:"после",pos:"adverb"},
  {kz:"әрқашан",en:"always",ru:"всегда",pos:"adverb"},
  {kz:"ешқашан",en:"never",ru:"никогда",pos:"adverb"},
  {kz:"кейде",en:"sometimes",ru:"иногда",pos:"adverb"},
  {kz:"жиі",en:"often",ru:"часто",pos:"adverb"},
  {kz:"сирек",en:"rarely",ru:"редко",pos:"adverb"},
  {kz:"дәл",en:"exactly",ru:"точно",pos:"adverb"},
  {kz:"бәрі",en:"all",ru:"все",pos:"pronoun"},
  {kz:"кейбір",en:"some",ru:"некоторые",pos:"pronoun"},
  {kz:"бірдеңе",en:"something",ru:"что-то",pos:"pronoun"},
  {kz:"ештеңе",en:"nothing",ru:"ничего",pos:"pronoun"},
  {kz:"көп",en:"many/much",ru:"много",pos:"adverb"},
  {kz:"аз",en:"few/little",ru:"мало",pos:"adverb"},
  {kz:"барлық",en:"every",ru:"каждый",pos:"adjective"},
  {kz:"басқа",en:"other",ru:"другой",pos:"adjective"},
  {kz:"осы",en:"this",ru:"этот",pos:"adjective"},
  {kz:"өзі",en:"self",ru:"сам",pos:"pronoun"},
  {kz:"үшін",en:"for",ru:"для",pos:"preposition"},
  {kz:"себепті",en:"because of",ru:"из-за",pos:"preposition"},
  {kz:"сайын",en:"according to",ru:"согласно",pos:"preposition"},
  {kz:"арқылы",en:"through",ru:"через",pos:"preposition"},
  {kz:"туралы",en:"about",ru:"о",pos:"preposition"},
  {kz:"бойынша",en:"according to",ru:"по",pos:"preposition"},
  {kz:"жынысты",en:"sexual",ru:"половой",pos:"adjective"},
  {kz:"жынысы",en:"gender/sex",ru:"пол",pos:"noun"},
  {kz:"балалық",en:"childhood",ru:"детство",pos:"noun"},
  {kz:"жастық",en:"youth",ru:"молодость",pos:"noun"},
  {kz:"орта",en:"middle/center",ru:"середина",pos:"noun"},
  {kz:"шет",en:"edge",ru:"край",pos:"noun"},
  {kz:"іш",en:"inside",ru:"внутри",pos:"noun"},
  {kz:"сырт",en:"outside",ru:"снаружи",pos:"noun"},
  {kz:"алды",en:"front",ru:"перед",pos:"noun"},
  {kz:"арт",en:"back/behind",ru:"зад",pos:"noun"},
  {kz:"үст",en:"top/above",ru:"верх",pos:"noun"},
  {kz:"асты",en:"bottom/below",ru:"низ",pos:"noun"},
  {kz:"жақын",en:"near",ru:"близкий",pos:"adjective"},
  {kz:"алыс",en:"far",ru:"далёкий",pos:"adjective"},
  {kz:"оң",en:"right",ru:"правый",pos:"adjective"},
  {kz:"сол",en:"left",ru:"левый",pos:"adjective"},
  {kz:"жаңа",en:"new",ru:"новый",pos:"adjective"},
  {kz:"өткен",en:"past/last",ru:"прошлый",pos:"adjective"},
  {kz:"келесі",en:"next",ru:"следующий",pos:"adjective"},
  {kz:"күрделі",en:"complex",ru:"сложный",pos:"adjective"},
  {kz:"қарапайым",en:"simple",ru:"простой",pos:"adjective"},
  {kz:"пайдалы",en:"useful",ru:"полезный",pos:"adjective"},
  {kz:"зиянды",en:"harmful",ru:"вредный",pos:"adjective"},
  {kz:"мүмкін",en:"possible",ru:"возможный",pos:"adjective"},
  {kz:"мүмкін емес",en:"impossible",ru:"невозможный",pos:"adjective"},
  {kz:"қажет",en:"necessary",ru:"нужный",pos:"adjective"},
  {kz:"қажет емес",en:"unnecessary",ru:"ненужный",pos:"adjective"},
  {kz:"дұрыс",en:"correct",ru:"правильный",pos:"adjective"},
  {kz:"қате",en:"wrong",ru:"неправильный",pos:"adjective"},
  {kz:"шынайы",en:"real",ru:"настоящий",pos:"adjective"},
  {kz:"жалған",en:"false",ru:"ложный",pos:"adjective"},
  {kz:"маңызды",en:"important",ru:"важный",pos:"adjective"},
  {kz:"маңызды емес",en:"unimportant",ru:"неважный",pos:"adjective"},
  {kz:"қызықты",en:"interesting",ru:"интересный",pos:"adjective"},
  {kz:"зейінсіз",en:"boring",ru:"скучный",pos:"adjective"},
  {kz:"қымбат",en:"expensive",ru:"дорогой",pos:"adjective"},
  {kz:"арзан",en:"cheap",ru:"дешёвый",pos:"adjective"},
  {kz:"дәмді",en:"tasty",ru:"вкусный",pos:"adjective"},
  {kz:"дәмсіз",en:"tasteless",ru:"безвкусный",pos:"adjective"},
  {kz:"хош иісті",en:"fragrant",ru:"ароматный",pos:"adjective"},
  {kz:"жағымды",en:"pleasant",ru:"приятный",pos:"adjective"},
  {kz:"жағымсыз",en:"unpleasant",ru:"неприятный",pos:"adjective"},
  {kz:"тәтті",en:"sweet",ru:"сладкий",pos:"adjective"},
  {kz:"ащы",en:"bitter",ru:"горький",pos:"adjective"},
  {kz:"тұзды",en:"salty",ru:"солёный",pos:"adjective"},
  {kz:"қышқыл",en:"sour",ru:"кислый",pos:"adjective"},
  {kz:"əлсіз",en:"weak",ru:"слабый",pos:"adjective"},
  {kz:"күшті",en:"strong",ru:"сильный",pos:"adjective"},
  {kz:"төзімді",en:"resistant",ru:"устойчивый",pos:"adjective"},
  {kz:"батыл",en:"brave",ru:"смелый",pos:"adjective"},
  {kz:"үрейлі",en:"scary",ru:"страшный",pos:"adjective"},
  {kz:"өжет",en:"stubborn",ru:"упрямый",pos:"adjective"},
  {kz:"бақытты",en:"happy",ru:"счастливый",pos:"adjective"},
  {kz:"бақытсыз",en:"unhappy",ru:"несчастный",pos:"adjective"},
  {kz:"қуанышты",en:"joyful",ru:"радостный",pos:"adjective"},
  {kz:"көңілді",en:"cheerful",ru:"весёлый",pos:"adjective"},
  {kz:"көңілсіз",en:"gloomy",ru:"грустный",pos:"adjective"},
  {kz:"шыншыл",en:"sincere",ru:"искренний",pos:"adjective"},
  {kz:"жалқау",en:"lazy",ru:"ленивый",pos:"adjective"},
  {kz:"еңбекқор",en:"hardworking",ru:"трудолюбивый",pos:"adjective"},
  {kz:"шебер",en:"skilled",ru:"умелый",pos:"adjective"},
  {kz:"əдепті",en:"polite",ru:"вежливый",pos:"adjective"},
  {kz:"өнегелі",en:"exemplary",ru:"образцовый",pos:"adjective"},
  {kz:"ұнамды",en:"attractive",ru:"привлекательный",pos:"adjective"},
  {kz:"жексұрын",en:"ugly",ru:"уродливый",pos:"adjective"},
  {kz:"жас",en:"young",ru:"молодой",pos:"adjective"},
  {kz:"кәрі",en:"old (of person)",ru:"старый (о человеке)",pos:"adjective"},
  {kz:"ақ",en:"white",ru:"белый",pos:"adjective"},
  {kz:"қара",en:"black",ru:"чёрный",pos:"adjective"},
  {kz:"қызыл",en:"red",ru:"красный",pos:"adjective"},
  {kz:"сары",en:"yellow",ru:"жёлтый",pos:"adjective"},
  {kz:"көк",en:"blue",ru:"синий",pos:"adjective"},
  {kz:"жасыл",en:"green",ru:"зелёный",pos:"adjective"},
  {kz:"күлгін",en:"purple",ru:"фиолетовый",pos:"adjective"},
  {kz:"қоңыр",en:"brown",ru:"коричневый",pos:"adjective"},
  {kz:"сұр",en:"grey",ru:"серый",pos:"adjective"},
  {kz:"түсті",en:"colored",ru:"цветной",pos:"adjective"},
  {kz:"түссіз",en:"colorless",ru:"бесцветный",pos:"adjective"},
  {kz:"домбық",en:"curly",ru:"кудрявый",pos:"adjective"},
  {kz:"түзу",en:"straight",ru:"прямой",pos:"adjective"},
  {kz:"қысқа",en:"short",ru:"короткий",pos:"adjective"},
  {kz:"ұзын",en:"long",ru:"длинный",pos:"adjective"},
  {kz:"жіңішке",en:"thin/slim",ru:"тонкий",pos:"adjective"},
  {kz:"жуан",en:"thick/fat",ru:"толстый",pos:"adjective"},
  {kz:"дөңгелек",en:"round",ru:"круглый",pos:"adjective"},
  {kz:"шаршы",en:"square",ru:"квадратный",pos:"adjective"},
  {kz:"сопақ",en:"oval",ru:"овальный",pos:"adjective"},
  {kz:"қатты",en:"solid/hard",ru:"твёрдый",pos:"adjective"},
  {kz:"сұйық",en:"liquid",ru:"жидкий",pos:"adjective"},
  {kz:"газтектес",en:"gaseous",ru:"газообразный",pos:"adjective"},
  {kz:"ыстық",en:"hot",ru:"горячий",pos:"adjective"},
  {kz:"суық",en:"cold",ru:"холодный",pos:"adjective"},
  {kz:"пісіру",en:"to cook",ru:"готовить",pos:"verb"},
  {kz:"шаю",en:"to wash",ru:"мыть",pos:"verb"},
  {kz:"тазалау",en:"to clean",ru:"чистить",pos:"verb"},
  {kz:"сыпыру",en:"to sweep",ru:"подметать",pos:"verb"},
  {kz:"үтіктеу",en:"to iron",ru:"гладить",pos:"verb"},
  {kz:"тігу",en:"to sew",ru:"шить",pos:"verb"},
  {kz:"жөндеу",en:"to repair",ru:"ремонтировать",pos:"verb"},
  {kz:"құрылыс",en:"construction",ru:"строительство",pos:"noun"},
  {kz:"үй",en:"house",ru:"дом",pos:"noun"},
  {kz:"пәтер",en:"apartment",ru:"квартира",pos:"noun"},
  {kz:"бөлме",en:"room",ru:"комната",pos:"noun"},
  {kz:"есіктұмпе",en:"doorknob",ru:"дверная ручка",pos:"noun"},
  {kz:"терезе",en:"window",ru:"окно",pos:"noun"},
  {kz:"қабырға",en:"wall",ru:"стена",pos:"noun"},
  {kz:"еден",en:"floor",ru:"пол",pos:"noun"},
  {kz:"төбе",en:"ceiling",ru:"потолок",pos:"noun"},
  {kz:"баспалдақ",en:"stairs",ru:"лестница",pos:"noun"},
  {kz:"гараж",en:"garage",ru:"гараж",pos:"noun"},
  {kz:"бағбан",en:"gardener",ru:"садовник",pos:"noun"},
  {kz:"бау",en:"garden bed",ru:"грядка",pos:"noun"},
  {kz:"гүл",en:"flower",ru:"цветок",pos:"noun"},
  {kz:"шөп",en:"grass",ru:"трава",pos:"noun"},
  {kz:"ағаш",en:"tree",ru:"дерево",pos:"noun"},
  {kz:"жапырақ",en:"leaf",ru:"лист",pos:"noun"},
  {kz:"гүлдеу",en:"to bloom",ru:"цвести",pos:"verb"},
  {kz:"көшет",en:"seedling",ru:"саженец",pos:"noun"},
  {kz:"тұқым",en:"seed",ru:"семя",pos:"noun"},
  {kz:"жеміс",en:"fruit",ru:"фрукт",pos:"noun"},
  {kz:"жидек",en:"berry",ru:"ягода",pos:"noun"},
  {kz:"көкөніс",en:"vegetable",ru:"овощь",pos:"noun"},
  {kz:"пияз",en:"onion",ru:"лук",pos:"noun"},
  {kz:"сарымсақ",en:"garlic",ru:"чеснок",pos:"noun"},
  {kz:"картоп",en:"potato",ru:"картофель",pos:"noun"},
  {kz:"қызанақ",en:"tomato",ru:"помидор",pos:"noun"},
  {kz:"бақлажан",en:"eggplant",ru:"баклажан",pos:"noun"},
  {kz:"қияр",en:"cucumber",ru:"огурец",pos:"noun"},
  {kz:"ас",en:"food",ru:"еда",pos:"noun"},
  {kz:"тамақ",en:"meal",ru:"пища",pos:"noun"},
  {kz:"наны",en:"bread",ru:"хлеб",pos:"noun"},
  {kz:"ет",en:"meat",ru:"мясо",pos:"noun"},
  {kz:"жұмыртқа",en:"egg",ru:"яйцо",pos:"noun"},
  {kz:"сүт",en:"milk",ru:"молоко",pos:"noun"},
  {kz:"ірімшік",en:"cheese",ru:"сыр",pos:"noun"},
  {kz:"май",en:"butter/oil",ru:"масло",pos:"noun"},
  {kz:"кетчуп",en:"ketchup",ru:"кетчуп",pos:"noun"},
  {kz:"дәрі",en:"medicine",ru:"лекарство",pos:"noun"},
  {kz:"ауру",en:"illness",ru:"болезнь",pos:"noun"},
  {kz:"емхана",en:"clinic",ru:"поликлиника",pos:"noun"},
  {kz:"дәрігер",en:"doctor",ru:"врач",pos:"noun"},
  {kz:"медбике",en:"nurse",ru:"медсестра",pos:"noun"},
  {kz:"аурухана",en:"hospital",ru:"больница",pos:"noun"},
  {kz:"дәріхана",en:"pharmacy",ru:"аптека",pos:"noun"},
  {kz:"жүрек",en:"heart",ru:"сердце",pos:"noun"},
  {kz:"бас",en:"head",ru:"голова",pos:"noun"},
  {kz:"дене",en:"body",ru:"тело",pos:"noun"},
  {kz:"қол",en:"hand",ru:"рука",pos:"noun"},
  {kz:"аяқ",en:"foot/leg",ru:"нога",pos:"noun"},
  {kz:"мойын",en:"neck",ru:"шея",pos:"noun"},
  {kz:"бет",en:"face",ru:"лицо",pos:"noun"},
  {kz:"көз",en:"eye",ru:"глаз",pos:"noun"},
  {kz:"құлақ",en:"ear",ru:"ухо",pos:"noun"},
  {kz:"мұрын",en:"nose",ru:"нос",pos:"noun"},
  {kz:"ауыз",en:"mouth",ru:"рот",pos:"noun"},
  {kz:"тіс",en:"tooth",ru:"зуб",pos:"noun"},
  {kz:"шаш",en:"hair",ru:"волосы",pos:"noun"},
  {kz:"тері",en:"skin",ru:"кожа",pos:"noun"},
  {kz:"сүйек",en:"bone",ru:"кость",pos:"noun"},
  {kz:"ет",en:"muscle",ru:"мышца",pos:"noun"},
  {kz:"қан",en:"blood",ru:"кровь",pos:"noun"},
  {kz:"жүйке",en:"nerve",ru:"нерв",pos:"noun"},
  {kz:"ми",en:"brain",ru:"мозг",pos:"noun"},
  {kz:"бауыр",en:"liver",ru:"печень",pos:"noun"},
  {kz:"өкпе",en:"lung",ru:"лёгкое",pos:"noun"},
  {kz:"бүйрек",en:"kidney",ru:"почка",pos:"noun"},
  {kz:"асқазан",en:"stomach",ru:"желудок",pos:"noun"},
  {kz:"ішек",en:"intestine",ru:"кишка",pos:"noun"},
  {kz:"жыныс",en:"gender/sex",ru:"пол",pos:"noun"},
  {kz:"жыныстық",en:"sexual",ru:"половой",pos:"adjective"},
  {kz:"буаз",en:"pregnant",ru:"беременная",pos:"adjective"},
  {kz:"емізу",en:"to breastfeed",ru:"кормить грудью",pos:"verb"},
  {kz:"нәрестелер",en:"infants",ru:"младенцы",pos:"noun"},
  {kz:"балалар",en:"children",ru:"дети",pos:"noun"},
  {kz:"жасөспірімдер",en:"teenagers",ru:"подростки",pos:"noun"},
  {kz:"жастар",en:"youth",ru:"молодёжь",pos:"noun"},
  {kz:"ересектер",en:"adults",ru:"взрослые",pos:"noun"},
  {kz:"қарттар",en:"elderly",ru:"пожилые",pos:"noun"},
  {kz:"отбасы",en:"family",ru:"семья",pos:"noun"},
  {kz:"неке",en:"marriage",ru:"брак",pos:"noun"},
  {kz:"некелесу",en:"to marry",ru:"жениться/выходить замуж",pos:"verb"},
  {kz:"жұп",en:"couple",ru:"пара",pos:"noun"},
  {kz:"сүйіспеншілік",en:"affection",ru:"привязанность",pos:"noun"},
  {kz:"махаббат",en:"love",ru:"любовь",pos:"noun"},
  {kz:"шыдау",en:"to tolerate",ru:"терпеть",pos:"verb"},
  {kz:"төзім",en:"patience",ru:"терпение",pos:"noun"},
  {kz:"кекету",en:"to avenge",ru:"мстить",pos:"verb"},
  {kz:"кешірім",en:"forgiveness",ru:"прощение",pos:"noun"},
  {kz:"кешіру",en:"to forgive",ru:"прощать",pos:"verb"},
  {kz:"сенім",en:"trust",ru:"доверие",pos:"noun"},
  {kz:"сену",en:"to believe",ru:"верить",pos:"verb"},
  {kz:"дін",en:"religion",ru:"религия",pos:"noun"},
  {kz:"алла",en:"God",ru:"Бог",pos:"noun"},
  {kz:"намаз",en:"prayer",ru:"молитва",pos:"noun"},
  {kz:"мешіт",en:"mosque",ru:"мечеть",pos:"noun"},
  {kz:"шіркеу",en:"church",ru:"церковь",pos:"noun"},
  {kz:"үгіт",en:"propaganda",ru:"пропаганда",pos:"noun"},
  {kz:"насихат",en:"preaching",ru:"проповедь",pos:"noun"},
  {kz:"абыз",en:"priest",ru:"жрец",pos:"noun"},
  {kz:"халық",en:"people/nation",ru:"народ",pos:"noun"},
  {kz:"ел",en:"country",ru:"страна",pos:"noun"},
  {kz:"мемлекет",en:"state",ru:"государство",pos:"noun"},
  {kz:"президент",en:"president",ru:"президент",pos:"noun"},
  {kz:"министр",en:"minister",ru:"министр",pos:"noun"},
  {kz:"депутат",en:"deputy",ru:"депутат",pos:"noun"},
  {kz:"заң",en:"law",ru:"закон",pos:"noun"},
  {kz:"сот",en:"court",ru:"суд",pos:"noun"},
  {kz:"түрме",en:"prison",ru:"тюрьма",pos:"noun"},
  {kz:"қылмыс",en:"crime",ru:"преступление",pos:"noun"},
  {kz:"қылмыскер",en:"criminal",ru:"преступник",pos:"noun"},
  {kz:"қару",en:"weapon",ru:"оружие",pos:"noun"},
  {kz:"соғыс",en:"war",ru:"война",pos:"noun"},
  {kz:"бейбітшілік",en:"peace",ru:"мир",pos:"noun"},
  {kz:"достастық",en:"friendship",ru:"дружба",pos:"noun"},
  {kz:"ынтымақ",en:"harmony",ru:"согласие",pos:"noun"},
  {kz:"шет мемлекет",en:"foreign country",ru:"иностранное государство",pos:"noun"},
  {kz:"шетелдік",en:"foreigner",ru:"иностранец",pos:"noun"},
  {kz:"азамат",en:"citizen",ru:"гражданин",pos:"noun"},
  {kz:"паспорт",en:"passport",ru:"паспорт",pos:"noun"},
  {kz:"виза",en:"visa",ru:"виза",pos:"noun"},
  {kz:"валюта",en:"currency",ru:"валюта",pos:"noun"},
  {kz:"теңге",en:"tenge",ru:"тенге",pos:"noun"},
  {kz:"доллар",en:"dollar",ru:"доллар",pos:"noun"},
  {kz:"евро",en:"euro",ru:"евро",pos:"noun"},
  {kz:"рубль",en:"ruble",ru:"рубль",pos:"noun"},
  {kz:"баға",en:"price",ru:"цена",pos:"noun"},
  {kz:"базар",en:"market",ru:"рынок",pos:"noun"},
  {kz:"дүкен",en:"shop",ru:"магазин",pos:"noun"},
  {kz:"орамды",en:"roll",ru:"рулон",pos:"noun"},
  {kz:"сатып алу",en:"to buy",ru:"покупать",pos:"verb"},
  {kz:"сату",en:"to sell",ru:"продавать",pos:"verb"},
  {kz:"ақша",en:"money",ru:"деньги",pos:"noun"},
  {kz:"банк",en:"bank",ru:"банк",pos:"noun"},
  {kz:"несие",en:"loan",ru:"кредит",pos:"noun"},
  {kz:"несие беру",en:"to lend",ru:"давать в долг",pos:"verb"},
  {kz:"несие алу",en:"to borrow",ru:"брать в долг",pos:"verb"},
  {kz:"есеп",en:"account",ru:"счёт",pos:"noun"},
  {kz:"есептеу",en:"to calculate",ru:"вычислять",pos:"verb"},
  {kz:"сан",en:"number",ru:"число",pos:"noun"},
  {kz:"цифра",en:"digit",ru:"цифра",pos:"noun"},
  {kz:"процент",en:"percent",ru:"процент",pos:"noun"},
  {kz:"қосу",en:"to add",ru:"складывать",pos:"verb"},
  {kz:"алу",en:"to subtract",ru:"вычитать",pos:"verb"},
  {kz:"көбейту",en:"to multiply",ru:"умножать",pos:"verb"},
  {kz:"бөлу",en:"to divide",ru:"делить",pos:"verb"},
  {kz:"тең",en:"equal",ru:"равный",pos:"adjective"},
  {kz:"теңдеу",en:"equation",ru:"уравнение",pos:"noun"},
  {kz:"формула",en:"formula",ru:"формула",pos:"noun"},
  {kz:"өлшем",en:"measurement",ru:"измерение",pos:"noun"},
  {kz:"салмақ",en:"weight",ru:"вес",pos:"noun"},
  {kz:"биіктік",en:"height",ru:"высота",pos:"noun"},
  {kz:"ені",en:"width",ru:"ширина",pos:"noun"},
  {kz:"тереңдік",en:"depth",ru:"глубина",pos:"noun"},
  {kz:"көлем",en:"volume",ru:"объём",pos:"noun"},
  {kz:"аумақ",en:"area",ru:"площадь",pos:"noun"},
  {kz:"қашықтық",en:"distance",ru:"расстояние",pos:"noun"},
  {kz:"жылдамдық",en:"speed",ru:"скорость",pos:"noun"},
  {kz:"уақыт",en:"time",ru:"время",pos:"noun"},
  {kz:"минут",en:"minute",ru:"минута",pos:"noun"},
  {kz:"сағат",en:"hour",ru:"час",pos:"noun"},
  {kz:"тәулік",en:"day (24 hours)",ru:"сутки",pos:"noun"},
  {kz:"апта",en:"week",ru:"неделя",pos:"noun"},
  {kz:"ай",en:"month",ru:"месяц",pos:"noun"},
  {kz:"жыл",en:"year",ru:"год",pos:"noun"},
  {kz:"ғасыр",en:"century",ru:"век",pos:"noun"},
  {kz:"мыңжылдық",en:"millennium",ru:"тысячелетие",pos:"noun"},
  {kz:"ғылым",en:"science",ru:"наука",pos:"noun"},
  {kz:"ғалым",en:"scientist",ru:"учёный",pos:"noun"},
  {kz:"зерттеу",en:"research",ru:"исследование",pos:"verb"},
  {kz:"технология",en:"technology",ru:"технология",pos:"noun"},
  {kz:"техника",en:"engineering",ru:"техника",pos:"noun"},
  {kz:"машина",en:"machine/car",ru:"машина",pos:"noun"},
  {kz:"автобус",en:"bus",ru:"автобус",pos:"noun"},
  {kz:"поезд",en:"train",ru:"поезд",pos:"noun"},
  {kz:"ұшақ",en:"airplane",ru:"самолёт",pos:"noun"},
  {kz:"кеме",en:"ship",ru:"корабль",pos:"noun"},
  {kz:"велосипед",en:"bicycle",ru:"велосипед",pos:"noun"},
  {kz:"мотоцикл",en:"motorcycle",ru:"мотоцикл",pos:"noun"},
  {kz:"автокөлік",en:"automobile",ru:"автомобиль",pos:"noun"},
  {kz:"жол",en:"road",ru:"дорога",pos:"noun"},
  {kz:"теміржол",en:"railway",ru:"железная дорога",pos:"noun"},
  {kz:"вокзал",en:"railway station",ru:"вокзал",pos:"noun"},
  {kz:"аэропорт",en:"airport",ru:"аэропорт",pos:"noun"},
  {kz:"порт",en:"port",ru:"порт",pos:"noun"},
  {kz:"көпір",en:"bridge",ru:"мост",pos:"noun"},
  {kz:"тунель",en:"tunnel",ru:"туннель",pos:"noun"},
  {kz:"өзен",en:"river",ru:"река",pos:"noun"},
  {kz:"көл",en:"lake",ru:"озеро",pos:"noun"},
  {kz:"теңіз",en:"sea",ru:"море",pos:"noun"},
  {kz:"мұхит",en:"ocean",ru:"океан",pos:"noun"},
  {kz:"тау",en:"mountain",ru:"гора",pos:"noun"},
  {kz:"жыра",en:"ravine",ru:"овраг",pos:"noun"},
  {kz:"дала",en:"steppe",ru:"степь",pos:"noun"},
  {kz:"шөл",en:"desert",ru:"пустыня",pos:"noun"},
  {kz:"орман",en:"forest",ru:"лес",pos:"noun"},
  {kz:"жер",en:"land",ru:"земля",pos:"noun"},
  {kz:"өзен",en:"river",ru:"река",pos:"noun"},
  {kz:"су",en:"water",ru:"вода",pos:"noun"},
  {kz:"мұз",en:"ice",ru:"лёд",pos:"noun"},
  {kz:"қар",en:"snow",ru:"снег",pos:"noun"},
  {kz:"жаңбыр",en:"rain",ru:"дождь",pos:"noun"},
  {kz:"жаяу",en:"on foot",ru:"пешком",pos:"adverb"},
  {kz:"жүгіру",en:"to run",ru:"бегать",pos:"verb"},
  {kz:"секіру",en:"to jump",ru:"прыгать",pos:"verb"},
  {kz:"жайлы",en:"comfortable",ru:"удобный",pos:"adjective"},
  {kz:"жайсыз",en:"uncomfortable",ru:"неудобный",pos:"adjective"},
  {kz:"еркін",en:"free",ru:"свободный",pos:"adjective"},
  {kz:"білім",en:"education",ru:"знание",pos:"noun"},
  {kz:"білім беру",en:"to educate",ru:"образовывать",pos:"verb"},
  {kz:"оқулық",en:"textbook",ru:"учебник",pos:"noun"},
  {kz:"кітапхана",en:"library",ru:"библиотека",pos:"noun"},
  {kz:"ғибадатхана",en:"temple",ru:"храм",pos:"noun"},
  {kz:"мектеп",en:"school",ru:"школа",pos:"noun"},
  {kz:"университет",en:"university",ru:"университет",pos:"noun"},
  {kz:"курс",en:"course",ru:"курс",pos:"noun"},
  {kz:"лекция",en:"lecture",ru:"лекция",pos:"noun"},
  {kz:"семинар",en:"seminar",ru:"семинар",pos:"noun"},
  {kz:"экзамен",en:"exam",ru:"экзамен",pos:"noun"},
  {kz:"диплом",en:"diploma",ru:"диплом",pos:"noun"},
  {kz:"бағдарлама",en:"program",ru:"программа",pos:"noun"},
  {kz:"жоспар",en:"plan",ru:"план",pos:"noun"},
  {kz:"мақсат",en:"goal",ru:"цель",pos:"noun"},
  {kz:"міндет",en:"task",ru:"задача",pos:"noun"},
  {kz:"мәселе",en:"problem",ru:"проблема",pos:"noun"},
  {kz:"шешім",en:"solution",ru:"решение",pos:"noun"},
  {kz:"тәжірибе",en:"experience",ru:"опыт",pos:"noun"},
  {kz:"дағды",en:"skill",ru:"навык",pos:"noun"},
  {kz:"шеберлік",en:"mastery",ru:"мастерство",pos:"noun"},
  {kz:"өнер",en:"art",ru:"искусство",pos:"noun"},
  {kz:"мәдениет",en:"culture",ru:"культура",pos:"noun"},
  {kz:"әдебиет",en:"literature",ru:"литература",pos:"noun"},
  {kz:"поэзия",en:"poetry",ru:"поэзия",pos:"noun"},
  {kz:"проза",en:"prose",ru:"проза",pos:"noun"},
  {kz:"роман",en:"novel",ru:"роман",pos:"noun"},
  {kz:"ӛлең",en:"poem",ru:"стихотворение",pos:"noun"},
  {kz:"əн",en:"song",ru:"песня",pos:"noun"},
  {kz:"музыка",en:"music",ru:"музыка",pos:"noun"},
  {kz:"саз",en:"melody",ru:"мелодия",pos:"noun"},
  {kz:"əуез",en:"tune",ru:"мотив",pos:"noun"},
  {kz:"би",en:"dance",ru:"танец",pos:"noun"},
  {kz:"театр",en:"theater",ru:"театр",pos:"noun"},
  {kz:"кино",en:"cinema",ru:"кино",pos:"noun"},
  {kz:"фильм",en:"film",ru:"фильм",pos:"noun"},
  {kz:"сурет",en:"picture",ru:"картина",pos:"noun"},
  {kz:"фотосурет",en:"photograph",ru:"фотография",pos:"noun"},
  {kz:"мүсін",en:"sculpture",ru:"скульптура",pos:"noun"},
  {kz:"сәндік",en:"decoration",ru:"украшение",pos:"noun"},
  {kz:"түс",en:"color",ru:"цвет",pos:"noun"},
  {kz:"сәуле",en:"ray",ru:"луч",pos:"noun"},
  {kz:"жарық",en:"light",ru:"свет",pos:"noun"},
  {kz:"көлеңке",en:"shadow",ru:"тень",pos:"noun"},
  {kz:"күзет",en:"guard",ru:"охрана",pos:"noun"},
  {kz:"күзетші",en:"guard (person)",ru:"охранник",pos:"noun"},
  {kz:"қауіп",en:"danger",ru:"опасность",pos:"noun"},
  {kz:"қауіпсіз",en:"safe",ru:"безопасный",pos:"adjective"},
  {kz:"сақтық",en:"caution",ru:"осторожность",pos:"noun"},
  {kz:"сақ",en:"careful",ru:"осторожный",pos:"adjective"},
  {kz:"байқау",en:"to notice",ru:"замечать",pos:"verb"},
  {kz:"назар",en:"attention",ru:"внимание",pos:"noun"},
  {kz:"зейін",en:"focus",ru:"внимание",pos:"noun"},
  {kz:"еске сақтау",en:"to remember",ru:"запоминать",pos:"verb"},
  {kz:"ұмыт",en:"to forget",ru:"забывать",pos:"verb"},
  {kz:"үміт",en:"hope",ru:"надежда",pos:"noun"},
  {kz:"сенім",en:"confidence",ru:"уверенность",pos:"noun"},
  {kz:"мазал",en:"worry",ru:"беспокойство",pos:"noun"},
  {kz:"мазалау",en:"to worry",ru:"беспокоить",pos:"verb"},
  {kz:"реніш",en:"resentment",ru:"обида",pos:"noun"},
  {kz:"қуаныш",en:"joy",ru:"радость",pos:"noun"},
  {kz:"көңіл",en:"mood",ru:"настроение",pos:"noun"},
  {kz:"ашу",en:"anger",ru:"гнев",pos:"noun"},
  {kz:"жиілену",en:"to get angry",ru:"злиться",pos:"verb"},
  {kz:"сөнбеу",en:"to go out (fire)",ru:"гаснуть",pos:"verb"},
  {kz:"сөндіру",en:"to extinguish",ru:"тушить",pos:"verb"},
  {kz:"жанып тұру",en:"to burn (intransitive)",ru:"гореть",pos:"verb"},
  {kz:"жағу",en:"to light (fire)",ru:"зажигать",pos:"verb"},
  {kz:"жарылу",en:"to explode",ru:"взрываться",pos:"verb"},
  {kz:"жарылыс",en:"explosion",ru:"взрыв",pos:"noun"},
  {kz:"үшmess",en:"crash",ru:"крушение",pos:"noun"},
  {kz:"сый",en:"gift",ru:"подарок",pos:"noun"},
  {kz:"сыйлау",en:"to give as gift",ru:"дарить",pos:"verb"},
  {kz:"алғыс",en:"gratitude",ru:"благодарность",pos:"noun"},
  {kz:"алғыс айту",en:"to thank",ru:"благодарить",pos:"verb"},
  {kz:"тілек",en:"wish",ru:"пожелание",pos:"noun"},
  {kz:"сәлем",en:"greeting",ru:"приветствие",pos:"noun"},
  {kz:"сәлемдесу",en:"to greet",ru:"приветствовать",pos:"verb"},
  {kz:"танысу",en:"to meet/get acquainted",ru:"знакомиться",pos:"verb"},
  {kz:"таныстыру",en:"to introduce",ru:"представлять",pos:"verb"},
  {kz:"қоштасу",en:"to say goodbye",ru:"прощаться",pos:"verb"},
  {kz:"рұқсат",en:"permission",ru:"разрешение",pos:"noun"},
  {kz:"рұқсат сұрау",en:"to ask permission",ru:"просить разрешение",pos:"verb"},
  {kz:"тыйым салу",en:"to forbid",ru:"запрещать",pos:"verb"},
  {kz:"бұйрық",en:"command/order",ru:"приказ",pos:"noun"},
  {kz:"бұйрық беру",en:"to command",ru:"приказывать",pos:"verb"},
  {kz:"өтініш",en:"request",ru:"просьба",pos:"noun"},
  {kz:"өтініш білдіру",en:"to request",ru:"просить",pos:"verb"},
  {kz:"келісім",en:"agreement",ru:"соглашение",pos:"noun"},
  {kz:"келісу",en:"to agree",ru:"соглашаться",pos:"verb"},
  {kz:"бас тарту",en:"to refuse",ru:"отказываться",pos:"verb"},
  {kz:"қабылдау",en:"to accept",ru:"принимать",pos:"verb"},
  {kz:"қабылдану",en:"to be accepted",ru:"быть принятым",pos:"verb"},
  {kz:"қатысу",en:"to participate",ru:"участвовать",pos:"verb"},
  {kz:"қатысушы",en:"participant",ru:"участник",pos:"noun"},
  {kz:"құрастыру",en:"to compose",ru:"составлять",pos:"verb"},
  {kz:"бөлшектеу",en:"to disassemble",ru:"разбирать",pos:"verb"},
  {kz:"жөндеу",en:"to repair",ru:"чинить",pos:"verb"},
  {kz:"бұзу",en:"to break/damage",ru:"ломать",pos:"verb"},
  {kz:"бұзылу",en:"to break down",ru:"ломаться",pos:"verb"},
  {kz:"сындыру",en:"to break (transitive)",ru:"разбивать",pos:"verb"},
  {kz:"сыну",en:"to break (intransitive)",ru:"разбиться",pos:"verb"},
  {kz:"созу",en:"to stretch",ru:"тянуть",pos:"verb"},
  {kz:"созылу",en:"to stretch (intransitive)",ru:"тянуться",pos:"verb"},
  {kz:"сығу",en:"to squeeze",ru:"сжимать",pos:"verb"},
  {kz:"сығылу",en:"to be squeezed",ru:"сжиматься",pos:"verb"},
  {kz:"басу",en:"to press",ru:"давить",pos:"verb"},
  {kz:"батыру",en:"to plunge",ru:"погружать",pos:"verb"},
  {kz:"батылу",en:"to plunge (intransitive)",ru:"погружаться",pos:"verb"},
  {kz:"шығару",en:"to take out",ru:"вынимать",pos:"verb"},
  {kz:"шығу",en:"to go out",ru:"выходить",pos:"verb"},
  {kz:"кіру",en:"to enter",ru:"входить",pos:"verb"},
  {kz:"қою",en:"to put",ru:"класть",pos:"verb"},
  {kz:"ұстау",en:"to hold",ru:"держать",pos:"verb"},
  {kz:"тасу",en:"to carry",ru:"нести",pos:"verb"},
  {kz:"желу",en:"to carry (heavy)",ru:"носить (тяжёлое)",pos:"verb"},
  {kz:"тарту",en:"to pull",ru:"тянуть",pos:"verb"},
  {kz:"итеру",en:"to push",ru:"толкать",pos:"verb"},
  {kz:"бұрау",en:"to twist",ru:"крутить",pos:"verb"},
  {kz:"бұралу",en:"to twist (intransitive)",ru:"крутиться",pos:"verb"},
  {kz:"бұғау",en:"to tie",ru:"привязывать",pos:"verb"},
  {kz:"шешу",en:"to solve",ru:"решать",pos:"verb"},
  {kz:"шешілу",en:"to be solved",ru:"решаться",pos:"verb"},
  {kz:"ашу",en:"to open",ru:"открывать",pos:"verb"},
  {kz:"жабылу",en:"to close (intransitive)",ru:"закрываться",pos:"verb"},
  {kz:"жабу",en:"to close (transitive)",ru:"закрывать",pos:"verb"},
  {kz:"жабысу",en:"to stick",ru:"приклеиваться",pos:"verb"},
  {kz:"жабыстыру",en:"to stick (transitive)",ru:"приклеивать",pos:"verb"},
  {kz:"сулау",en:"to wet",ru:"мочить",pos:"verb"},
  {kz:"сулану",en:"to get wet",ru:"мокнуть",pos:"verb"},
  {kz:"кептіру",en:"to dry (transitive)",ru:"сушить",pos:"verb"},
  {kz:"кептену",en:"to dry (intransitive)",ru:"сохнуть",pos:"verb"},
  {kz:"құрғату",en:"to make dry",ru:"высушивать",pos:"verb"},
  {kz:"суыту",en:"to cool",ru:"охлаждать",pos:"verb"},
  {kz:"қыздыру",en:"to heat",ru:"нагревать",pos:"verb"},
  {kz:"қайнату",en:"to boil",ru:"кипятить",pos:"verb"},
  {kz:"еріту",en:"to melt",ru:"растапливать",pos:"verb"},
  {kz:"мұздату",en:"to freeze",ru:"замораживать",pos:"verb"},
  {kz:"күйдіру",en:"to burn (transitive)",ru:"обжигать",pos:"verb"},
  {kz:"күйу",en:"to burn (intransitive)",ru:"обжигаться",pos:"verb"},
  {kz:"улау",en:"to poison",ru:"травить",pos:"verb"},
  {kz:"улану",en:"to get poisoned",ru:"травиться",pos:"verb"},
  {kz:"егу",en:"to inject",ru:"делать укол",pos:"verb"},
  {kz:"жазылу",en:"to register",ru:"записываться",pos:"verb"},
  {kz:"жазба",en:"note",ru:"запись",pos:"noun"},
  {kz:"кітап",en:"book",ru:"книга",pos:"noun"},
  {kz:"қағаз",en:"paper",ru:"бумага",pos:"noun"},
  {kz:"қалам",en:"pen",ru:"ручка",pos:"noun"},
  {kz:"қарындаш",en:"pencil",ru:"карандаш",pos:"noun"},
  {kz:"сызғыш",en:"ruler",ru:"линейка",pos:"noun"},
  {kz:"өшіргіш",en:"eraser",ru:"ластик",pos:"noun"},
  {kz:"парта",en:"desk",ru:"парта",pos:"noun"},
  {kz:"доска",en:"board",ru:"доска",pos:"noun"},
  {kz:"мәлімдеме",en:"statement",ru:"заявление",pos:"noun"},
  {kz:"хат",en:"letter",ru:"письмо",pos:"noun"},
  {kz:"конверт",en:"envelope",ru:"конверт",pos:"noun"},
  {kz:"марка",en:"stamp",ru:"марка",pos:"noun"},
  {kz:"телефон",en:"telephone",ru:"телефон",pos:"noun"},
  {kz:"хабарлама",en:"message",ru:"сообщение",pos:"noun"},
  {kz:"хабар",en:"news",ru:"новость",pos:"noun"},
  {kz:"жеделхат",en:"telegram",ru:"телеграмма",pos:"noun"},
  {kz:"факс",en:"fax",ru:"факс",pos:"noun"},
  {kz:"интернет",en:"internet",ru:"интернет",pos:"noun"},
  {kz:"компьютер",en:"computer",ru:"компьютер",pos:"noun"},
  {kz:"экран",en:"screen",ru:"экран",pos:"noun"},
  {kz:"пернетақта",en:"keyboard",ru:"клавиатура",pos:"noun"},
  {kz:"тышқан",en:"mouse",ru:"мышь",pos:"noun"},
  {kz:"принтер",en:"printer",ru:"принтер",pos:"noun"},
  {kz:"сканер",en:"scanner",ru:"сканер",pos:"noun"},
  {kz:"программалық жабдық",en:"software",ru:"программное обеспечение",pos:"noun"},
  {kz:"ақпарат",en:"information",ru:"информация",pos:"noun"},
  {kz:"дерек",en:"data",ru:"данные",pos:"noun"},
  {kz:"файл",en:"file",ru:"файл",pos:"noun"},
  {kz:"бума",en:"folder",ru:"папка",pos:"noun"},
  {kz:"мәтін",en:"text",ru:"текст",pos:"noun"},
  {kz:"сөз",en:"word",ru:"слово",pos:"noun"},
  {kz:"сөйлем",en:"sentence",ru:"предложение",pos:"noun"},
  {kz:"абзац",en:"paragraph",ru:"абзац",pos:"noun"},
  {kz:"тақырып",en:"topic",ru:"тема",pos:"noun"},
  {kz:"мазмұн",en:"content",ru:"содержание",pos:"noun"},
  {kz:"мән",en:"meaning",ru:"значение",pos:"noun"},
  {kz:"түсіндірме",en:"explanation",ru:"объяснение",pos:"noun"},
  {kz:"сипаттама",en:"description",ru:"описание",pos:"noun"},
  {kz:"мүше",en:"member",ru:"член",pos:"noun"},
  {kz:"түр",en:"type",ru:"тип",pos:"noun"},
  {kz:"түрі",en:"kind",ru:"вид",pos:"noun"},
  {kz:"әдіс",en:"method",ru:"метод",pos:"noun"},
  {kz:"жол",en:"way/method",ru:"способ",pos:"noun"},
  {kz:"әдіснама",en:"methodology",ru:"методология",pos:"noun"},
  {kz:"теория",en:"theory",ru:"теория",pos:"noun"},
  {kz:"практика",en:"practice",ru:"практика",pos:"noun"},
  {kz:"принцип",en:"principle",ru:"принцип",pos:"noun"},
  {kz:"ереже",en:"rule",ru:"правило",pos:"noun"},
  {kz:"заң",en:"law",ru:"закон",pos:"noun"},
  {kz:"стандарт",en:"standard",ru:"стандарт",pos:"noun"},
  {kz:"норма",en:"norm",ru:"норма",pos:"noun"},
  {kz:"шек",en:"limit",ru:"предел",pos:"noun"},
  {kz:"шектеу",en:"to limit",ru:"ограничивать",pos:"verb"},
  {kz:"рұқсат ету",en:"to allow",ru:"разрешать",pos:"verb"},
  {kz:"тыйым салу",en:"to forbid",ru:"запрещать",pos:"verb"},
  {kz:"міндеттеу",en:"to obligate",ru:"обязывать",pos:"verb"},
  {kz:"құқық",en:"law/right",ru:"право",pos:"noun"},
  {kz:"міндет",en:"duty",ru:"обязанность",pos:"noun"},
  {kz:"жауапкершілік",en:"responsibility",ru:"ответственность",pos:"noun"},
  {kz:"азаматтық",en:"civil",ru:"гражданский",pos:"adjective"},
  {kz:"қылмыстық",en:"criminal",ru:"уголовный",pos:"adjective"},
  {kz:"әкімшілік",en:"administrative",ru:"административный",pos:"adjective"},
  {kz:"конституциялық",en:"constitutional",ru:"конституционный",pos:"adjective"},
  {kz:"халықаралық",en:"international",ru:"международный",pos:"adjective"},
  {kz:"елшілік",en:"embassy",ru:"посольство",pos:"noun"},
  {kz:"консулдық",en:"consulate",ru:"консульство",pos:"noun"},
  {kz:"виза",en:"visa",ru:"виза",pos:"noun"},
  {kz:"шекара",en:"border",ru:"граница",pos:"noun"},
  {kz:"мит",en:"customs",ru:"таможня",pos:"noun"},
  {kz:"вакцина",en:"vaccine",ru:"вакцина",pos:"noun"},
  {kz:"карантин",en:"quarantine",ru:"карантин",pos:"noun"},
  {kz:"эпидемия",en:"epidemic",ru:"эпидемия",pos:"noun"},
  {kz:"пандемия",en:"pandemic",ru:"пандемия",pos:"noun"},
  {kz:"у",en:"poison",ru:"яд",pos:"noun"},
  {kz:"егу",en:"injection",ru:"укол",pos:"noun"},
  {kz:"емдеу",en:"treatment",ru:"лечение",pos:"noun"},
  {kz:"ем",en:"medicine/drug",ru:"лекарство",pos:"noun"},
  {kz:"дәрі-дəрмек",en:"medication",ru:"медикаменты",pos:"noun"},
  {kz:"процедура",en:"procedure",ru:"процедура",pos:"noun"},
  {kz:"операция",en:"operation",ru:"операция",pos:"noun"},
  {kz:"скрининг",en:"screening",ru:"скрининг",pos:"noun"},
  {kz:"тест",en:"test",ru:"тест",pos:"noun"},
  {kz:"анализ",en:"analysis",ru:"анализ",pos:"noun"},
  {kz:"рентген",en:"X-ray",ru:"рентген",pos:"noun"},
  {kz:"УЗИ",en:"ultrasound",ru:"УЗИ",pos:"noun"},
  {kz:"ЭКГ",en:"ECG",ru:"ЭКГ",pos:"noun"},
  {kz:"балалар азық",en:"baby food",ru:"детское питание",pos:"noun"},
  {kz:"сұлы",en:"oats",ru:"овёс",pos:"noun"},
  {kz:"күріш",en:"rice",ru:"рис",pos:"noun"},
  {kz:"бидай",en:"wheat",ru:"пшеница",pos:"noun"},
  {kz:"арпа",en:"barley",ru:"ячмень",pos:"noun"},
  {kz:"жүгері",en:"corn",ru:"кукуруза",pos:"noun"},
  {kz:"қарақұмық",en:"buckwheat",ru:"гречка",pos:"noun"},
  {kz:"сорпо",en:"soup",ru:"суп",pos:"noun"},
  {kz:"борщ",en:"borscht",ru:"борщ",pos:"noun"},
  {kz:"палау",en:"pilaf",ru:"плов",pos:"noun"},
  {kz:"манты",en:"manty",ru:"манты",pos:"noun"},
  {kz:"самса",en:"samsa",ru:"самса",pos:"noun"},
  {kz:"лағман",en:"lagman",ru:"лагман",pos:"noun"},
  {kz:"бесбармак",en:"beshbarmak",ru:"бешбармак",pos:"noun"},
  {kz:"шәй",en:"tea",ru:"чай",pos:"noun"},
  {kz:"кофе",en:"coffee",ru:"кофе",pos:"noun"},
  {kz:"какао",en:"cocoa",ru:"какао",pos:"noun"},
  {kz:"шырын",en:"juice",ru:"сок",pos:"noun"},
  {kz:"сусын",en:"drink",ru:"напиток",pos:"noun"},
  {kz:"спиртті сусын",en:"alcoholic drink",ru:"алкогольный напиток",pos:"noun"},
  {kz:"сыра",en:"beer",ru:"пиво",pos:"noun"},
  {kz:"шарап",en:"wine",ru:"вино",pos:"noun"},
  {kz:"водка",en:"vodka",ru:"водка",pos:"noun"},
  {kz:"шылым",en:"cigarette",ru:"сигарета",pos:"noun"},
  {kz:"шылым шегу",en:"to smoke",ru:"курить",pos:"verb"},
  {kz:"орамал",en:"scarf",ru:"платок",pos:"noun"},
  {kz:"Жейде",en:"shirt",ru:"рубашка",pos:"noun"},
  {kz:"көйлек",en:"dress",ru:"платье",pos:"noun"},
  {kz:"костюм",en:"suit",ru:"костюм",pos:"noun"},
  {kz:"шемпүр",en:"underwear",ru:"нижнее бельё",pos:"noun"},
  {kz:"шұлық",en:"socks",ru:"носки",pos:"noun"},
  {kz:"етік",en:"boots",ru:"сапоги",pos:"noun"},
  {kz:"туфли",en:"shoes",ru:"туфли",pos:"noun"},
  {kz:"қалпақ",en:"hat",ru:"шляпа",pos:"noun"},
  {kz:"қолғап",en:"gloves",ru:"перчатки",pos:"noun"},
  {kz:"жамылғы",en:"clothing",ru:"одежда",pos:"noun"},
  {kz:"баскиім",en:"hat",ru:"головной убор",pos:"noun"},
  {kz:"балалар киімі",en:"children's clothing",ru:"детская одежда",pos:"noun"},
  {kz:"спорттық киім",en:"sportswear",ru:"спортивная одежда",pos:"noun"},
  {kz:"жиhаз",en:"furniture",ru:"мебель",pos:"noun"},
  {kz:"орындық",en:"chair",ru:"стул",pos:"noun"},
  {kz:"үстел",en:"table",ru:"стол",pos:"noun"},
  {kz:"шкаф",en:"wardrobe",ru:"шкаф",pos:"noun"},
  {kz:"төсек",en:"bed",ru:"кровать",pos:"noun"},
  {kz:"диван",en:"sofa",ru:"диван",pos:"noun"},
  {kz:"жиһаз",en:"furniture",ru:"мебель",pos:"noun"},
  {kz:"жылытқыш",en:"heater",ru:"обогреватель",pos:"noun"},
  {kz:"кондиционер",en:"air conditioner",ru:"кондиционер",pos:"noun"},
  {kz:"теледидар",en:"television",ru:"телевизор",pos:"noun"},
  {kz:"тоңазытқыш",en:"refrigerator",ru:"холодильник",pos:"noun"},
  {kz:"пеш",en:"stove",ru:"печь",pos:"noun"},
  {kz:"микротолқынды пеш",en:"microwave",ru:"микроволновка",pos:"noun"},
  {kz:"шаңсорғыш",en:"vacuum cleaner",ru:"пылесос",pos:"noun"},
  {kz:"киім жуғыш машина",en:"washing machine",ru:"стиральная машина",pos:"noun"},
  {kz:"ыдыс жуғыш машина",en:"dishwasher",ru:"посудомоечная машина",pos:"noun"},
  {kz:"шара",en:"cup",ru:"чаша",pos:"noun"},
  {kz:"-тостаған",en:"bowl",ru:"миска",pos:"noun"},
  {kz:"табақ",en:"plate",ru:"тарелка",pos:"noun"},
  {kz:"қасық",en:"spoon",ru:"ложка",pos:"noun"},
  {kz:"шанышқы",en:"fork",ru:"вилка",pos:"noun"},
  {kz:"пышақ",en:"knife",ru:"нож",pos:"noun"},
  {kz:"кесе",en:"glass",ru:"стакан",pos:"noun"},
  {kz:"құмыра",en:"pitcher",ru:"кувшин",pos:"noun"},
  {kz:"жылыту",en:"heating",ru:"отопление",pos:"noun"},
  {kz:"су құбыры",en:"water supply",ru:"водопровод",pos:"noun"},
  {kz:"арна",en:"channel",ru:"канал",pos:"noun"},
  {kz:"газ",en:"gas",ru:"газ",pos:"noun"},
  {kz:"электр",en:"electricity",ru:"электричество",pos:"noun"},
  {kz:"энергия",en:"energy",ru:"энергия",pos:"noun"},
  {kz:"жарық",en:"light",ru:"свет",pos:"noun"},
  {kz:"қараңғылық",en:"darkness",ru:"темнота",pos:"noun"},
  {kz:"күн шығыс",en:"sunrise",ru:"восход солнца",pos:"noun"},
  {kz:"күн бату",en:"sunset",ru:"закат солнца",pos:"noun"},
  {kz:"таң",en:"dawn",ru:"рассвет",pos:"noun"},
  {kz:"кеш",en:"evening",ru:"вечер",pos:"noun"},
  {kz:"түн",en:"night",ru:"ночь",pos:"noun"},
  {kz:"жарты түн",en:"midnight",ru:"полночь",pos:"noun"},
  {kz:"тағам",en:"dish (food)",ru:"блюдо",pos:"noun"},
  {kz:"мереке",en:"holiday",ru:"праздник",pos:"noun"},
  {kz:"туған күн",en:"birthday",ru:"день рождения",pos:"noun"},
  {kz:"той",en:"wedding feast",ru:"свадьба",pos:"noun"},
  {kz:"жерлеу",en:"burial",ru:"похороны",pos:"noun"},
  {kz:"аналық",en:"maternal",ru:"материнский",pos:"adjective"},
  {kz:"әкелік",en:"paternal",ru:"отцовский",pos:"adjective"},
  {kz:"бауырлар",en:"siblings",ru:"братья и сёстры",pos:"noun"},
  {kz:"жұбай",en:"spouse",ru:"супруг",pos:"noun"},
  {kz:"жұбайы",en:"spouse (his/her)",ru:"супруга/супруг",pos:"noun"},
  {kz:"жыныстық қатынас",en:"sexual intercourse",ru:"половой акт",pos:"noun"},
  {kz:"жүктілік",en:"pregnancy",ru:"беременность",pos:"noun"},
  {kz:"босану",en:"childbirth",ru:"роды",pos:"noun"},
  {kz:"баланы тамақтандыру",en:"feeding a child",ru:"кормление ребёнка",pos:"noun"},
  {kz:"балалар бөлмесі",en:"nursery",ru:"детская комната",pos:"noun"},
  {kz:"əдемілік",en:"beauty",ru:"красота",pos:"noun"},
  {kz:"əдемілендіру",en:"beautification",ru:"украшение",pos:"verb"},
  {kz:"макияж",en:"makeup",ru:"макияж",pos:"noun"},
  {kz:"маникюр",en:"manicure",ru:"маникюр",pos:"noun"},
  {kz:"педикюр",en:"pedicure",ru:"педикюр",pos:"noun"},
  {kz:"шаш жаңа",en:"haircut",ru:"стрижка",pos:"noun"},
  {kz:"салт",en:"tradition",ru:"традиция",pos:"noun"},
  {kz:"əдет",en:"custom",ru:"обычай",pos:"noun"},
  {kz:"рəсім",en:"ceremony",ru:"церемония",pos:"noun"},
  {kz:"мəдени шара",en:"cultural event",ru:"культурное мероприятие",pos:"noun"},
  {kz:"концерт",en:"concert",ru:"концерт",pos:"noun"},
  {kz:"көрме",en:"exhibition",ru:"выставка",pos:"noun"},
  {kz:"фестиваль",en:"festival",ru:"фестиваль",pos:"noun"},
  {kz:"сайыс",en:"competition",ru:"соревнование",pos:"noun"},
  {kz:"жарыс",en:"race",ru:"гонка",pos:"noun"},
  {kz:"ойын",en:"game",ru:"игра",pos:"noun"},
  {kz:"спорт",en:"sport",ru:"спорт",pos:"noun"},
  {kz:"футбол",en:"football",ru:"футбол",pos:"noun"},
  {kz:"хоккей",en:"hockey",ru:"хоккей",pos:"noun"},
  {kz:"баскетбол",en:"basketball",ru:"баскетбол",pos:"noun"},
  {kz:"волейбол",en:"volleyball",ru:"вололейбол",pos:"noun"},
  {kz:"тенис",en:"tennis",ru:"теннис",pos:"noun"},
  {kz:"бағдарлама",en:"program",ru:"программа",pos:"noun"},
  {kz:"жаңалық",en:"news",ru:"новость",pos:"noun"},
  {kz:"хабарлар",en:"news (broadcast)",ru:"новости",pos:"noun"},
  {kz:"газет",en:"newspaper",ru:"газета",pos:"noun"},
  {kz:"журнал",en:"magazine",ru:"журнал",pos:"noun"},
  {kz:"кітап",en:"book",ru:"книга",pos:"noun"},
  {kz:"энциклопедия",en:"encyclopedia",ru:"энциклопедия",pos:"noun"},
  {kz:"сөздік",en:"dictionary",ru:"словарь",pos:"noun"},
  {kz:"анықтамалық",en:"reference book",ru:"справочник",pos:"noun"},
  {kz:"автор",en:"author",ru:"автор",pos:"noun"},
  {kz:"жазушы",en:"writer",ru:"писатель",pos:"noun"},
  {kz:"ақын",en:"poet",ru:"поэт",pos:"noun"},
  {kz:"суретші",en:"artist",ru:"художник",pos:"noun"},
  {kz:"журналист",en:"journalist",ru:"журналист",pos:"noun"},
  {kz:"фотограф",en:"photographer",ru:"фотограф",pos:"noun"},
  {kz:"режиссер",en:"director",ru:"режиссёр",pos:"noun"},
  {kz:"актер",en:"actor",ru:"актёр",pos:"noun"},
  {kz:"әнші",en:"singer",ru:"певец",pos:"noun"},
  {kz:"биші",en:"dancer",ru:"танцор",pos:"noun"},
  {kz:"суретші",en:"painter",ru:"художник",pos:"noun"},
  {kz:"композитор",en:"composer",ru:"композитор",pos:"noun"},
  {kz:"дирижер",en:"conductor",ru:"дирижёр",pos:"noun"},
  {kz:"аспаз",en:"chef",ru:"шеф-повар",pos:"noun"},
  {kz:"журналистика",en:"journalism",ru:"журналистика",pos:"noun"},
  {kz:"жарнама",en:"advertising",ru:"реклама",pos:"noun"},
  {kz:"маркетинг",en:"marketing",ru:"маркетинг",pos:"noun"},
  {kz:"бухгалтерия",en:"accounting",ru:"бухгалтерия",pos:"noun"},
  {kz:"есеп",en:"calculation",ru:"расчёт",pos:"noun"},
  {kz:"аудит",en:"audit",ru:"аудит",pos:"noun"},
  {kz:"менеджмент",en:"management",ru:"менеджмент",pos:"noun"},
  {kz:"басқару",en:"management/control",ru:"управление",pos:"noun"},
  {kz:"директор",en:"director",ru:"директор",pos:"noun"},
  {kz:"басшы",en:"leader",ru:"руководитель",pos:"noun"},
  {kz:"қызметкер",en:"employee",ru:"сотрудник",pos:"noun"},
  {kz:"жұмыскер",en:"worker",ru:"работник",pos:"noun"},
  {kz:"маман",en:"specialist",ru:"специалист",pos:"noun"},
  {kz:"инженер",en:"engineer",ru:"инженер",pos:"noun"},
  {kz:"техник",en:"technician",ru:"техник",pos:"noun"},
  {kz:"механик",en:"mechanic",ru:"механик",pos:"noun"},
  {kz:"электрик",en:"electrician",ru:"электрик",pos:"noun"},
  {kz:"сантехник",en:"plumber",ru:"сантехник",pos:"noun"},
  {kz:"құрылысшы",en:"builder",ru:"строитель",pos:"noun"},
  {kz:"архитектор",en:"architect",ru:"архитектор",pos:"noun"},
  {kz:"дизайнер",en:"designer",ru:"дизайнер",pos:"noun"},
  {kz:"программист",en:"programmer",ru:"программист",pos:"noun"},
  {kz:"веб-әзірлеуші",en:"web developer",ru:"веб-разработчик",pos:"noun"},
  {kz:"әкімші",en:"administrator",ru:"администратор",pos:"noun"},
  {kz:"хатшы",en:"secretary",ru:"секретарь",pos:"noun"},
  {kz:"кеңсе",en:"office",ru:"офис",pos:"noun"},
  {kz:"кеңсе жабдықтары",en:"office supplies",ru:"канцелярские принадлежности",pos:"noun"},
  {kz:"компания",en:"company",ru:"компания",pos:"noun"},
  {kz:"фирма",en:"firm",ru:"фирма",pos:"noun"},
  {kz:"кəсіпорын",en:"enterprise",ru:"предприятие",pos:"noun"},
  {kz:"зауыт",en:"factory",ru:"завод",pos:"noun"},
  {kz:"цех",en:"workshop",ru:"цех",pos:"noun"},
  {kz:"склад",en:"warehouse",ru:"склад",pos:"noun"},
  {kz:"дүкен",en:"shop",ru:"магазин",pos:"noun"},
  {kz:"supermarket",en:"supermarket",ru:"супермаркет",pos:"noun"},
  {kz:"дəріхана",en:"pharmacy",ru:"аптека",pos:"noun"},
  {kz:"емхана",en:"clinic",ru:"поликлиника",pos:"noun"},
  {kz:"аурухана",en:"hospital",ru:"больница",pos:"noun"},
  {kz:"мектеп",en:"school",ru:"школа",pos:"noun"},
  {kz:"мектепке дейінгі мекеме",en:"preschool",ru:"дошкольное учреждение",pos:"noun"},
  {kz:"балабақша",en:"kindergarten",ru:"детский сад",pos:"noun"},
  {kz:"колледж",en:"college",ru:"колледж",pos:"noun"},
  {kz:"университет",en:"university",ru:"университет",pos:"noun"},
  {kz:"институт",en:"institute",ru:"институт",pos:"noun"},
  {kz:"академия",en:"academy",ru:"академия",pos:"noun"},
  {kz:"курс",en:"course",ru:"курс",pos:"noun"},
  {kz:"сабақ",en:"lesson",ru:"урок",pos:"noun"},
  {kz:"сөздік",en:"vocabulary",ru:"словарный запас",pos:"noun"},
  {kz:"грамматика",en:"grammar",ru:"грамматика",pos:"noun"},
  {kz:"фонетика",en:"phonetics",ru:"фонетика",pos:"noun"},
  {kz:"лексика",en:"lexicon",ru:"лексика",pos:"noun"},
  {kz:"сөз",en:"word",ru:"слово",pos:"noun"},
  {kz:"əріп",en:"letter (of alphabet)",ru:"буква",pos:"noun"},
  {kz:"дыбыс",en:"sound",ru:"звук",pos:"noun"},
  {kz:"бунақ",en:"syllable",ru:"слог",pos:"noun"},
  {kz:"сөйлем",en:"sentence",ru:"предложение",pos:"noun"},
  {kz:"мәтін",en:"text",ru:"текст",pos:"noun"},
  {kz:"абзац",en:"paragraph",ru:"абзац",pos:"noun"},
  {kz:"тақырып",en:"topic",ru:"тема",pos:"noun"},
  {kz:"мазмұн",en:"content",ru:"содержание",pos:"noun"},
  {kz:"мағына",en:"meaning",ru:"значение",pos:"noun"},
  {kz:"синоним",en:"synonym",ru:"синоним",pos:"noun"},
  {kz:"антоним",en:"antonym",ru:"антоним",pos:"noun"},
  {kz:"омоним",en:"homonym",ru:"омоним",pos:"noun"},
  {kz:"фразеология",en:"phraseology",ru:"фразеология",pos:"noun"},
  {kz:"идиома",en:"idiom",ru:"идиома",pos:"noun"},
  {kz:"нақыл",en:"proverb",ru:"пословица",pos:"noun"},
  {kz:"мақал",en:"saying",ru:"поговорка",pos:"noun"},
  {kz:"жұмбақ",en:"riddle",ru:"загадка",pos:"noun"},
  {kz:"өлең",en:"poem",ru:"стихотворение",pos:"noun"},
  {kz:"поэма",en:"poem (long)",ru:"поэма",pos:"noun"},
  {kz:"роман",en:"novel",ru:"роман",pos:"noun"},
  {kz:"повесть",en:"novella",ru:"повесть",pos:"noun"},
  {kz:"əңгіме",en:"story",ru:"рассказ",pos:"noun"},
  {kz:"новелла",en:"novella",ru:"новелла",pos:"noun"},
  {kz:"фельетон",en:"satire",ru:"фельетон",pos:"noun"},
  {kz:"памфлет",en:"pamphlet",ru:"памфлет",pos:"noun"},
  {kz:"баяндама",en:"report",ru:"доклад",pos:"noun"},
  {kz:"презентация",en:"presentation",ru:"презентация",pos:"noun"},
  {kz:"реферат",en:"abstract",ru:"реферат",pos:"noun"},
  {kz:"диссертация",en:"dissertation",ru:"диссертация",pos:"noun"},
  {kz:"зияткерлік меншік",en:"intellectual property",ru:"интеллектуальная собственность",pos:"noun"},
  {kz:"авторлық құқық",en:"copyright",ru:"авторское право",pos:"noun"},
  {kz:"патент",en:"patent",ru:"патент",pos:"noun"},
  {kz:"тəжірибе",en:"practice",ru:"практика",pos:"noun"},
  {kz:"стажировка",en:"internship",ru:"стажировка",pos:"noun"},
  {kz:"жұмыс іздеу",en:"job search",ru:"поиск работы",pos:"verb"},
  {kz:"жұмысқа орналасу",en:"employment",ru:"трудоустройство",pos:"verb"},
  {kz:"еңбек шарты",en:"labor contract",ru:"трудовой договор",pos:"noun"},
  {kz:"жалақы",en:"salary",ru:"зарплата",pos:"noun"},
  {kz:"дель",en:"bonus",ru:"премия",pos:"noun"},
  {kz:"демалыс",en:"vacation",ru:"отпуск",pos:"noun"},
  {kz:"зейнетақы",en:"pension",ru:"пенсия",pos:"noun"},
  {kz:"мерзім",en:"term",ru:"срок",pos:"noun"},
  {kz:"мерзімді",en:"periodical",ru:"периодический",pos:"adjective"},
  {kz:"жылдық",en:"annual",ru:"ежегодный",pos:"adjective"},
  {kz:"айлық",en:"monthly",ru:"ежемесячный",pos:"adjective"},
  {kz:"күнделікті",en:"daily",ru:"ежедневный",pos:"adjective"},
  {kz:"сабақтас",en:"related",ru:"связанный",pos:"adjective"},
  {kz:"тəуелсіз",en:"independent",ru:"независимый",pos:"adjective"},
  {kz:"тəуелді",en:"dependent",ru:"зависимый",pos:"adjective"},
  {kz:"бəсекелес",en:"competitive",ru:"конкурентный",pos:"adjective"},
  {kz:"тиімді",en:"effective",ru:"эффективный",pos:"adjective"},
  {kz:"тиімсіз",en:"ineffective",ru:"неэффективный",pos:"adjective"},
  {kz:"пайдалы",en:"useful",ru:"полезный",pos:"adjective"},
  {kz:"зиянды",en:"harmful",ru:"вредный",pos:"adjective"},
  {kz:"кəсіби",en:"professional",ru:"профессиональный",pos:"adjective"},
  {kz:"бейберекет",en:"careless",ru:"безответственный",pos:"adjective"},
  {kz:"тиянақты",en:"thorough",ru:"основательный",pos:"adjective"},
  {kz:"жүйелі",en:"systematic",ru:"систематический",pos:"adjective"},
  {kz:"ретімен",en:"in order",ru:"по порядку",pos:"adverb"},
  {kz:"реттеу",en:"regulation",ru:"регулирование",pos:"noun"},
  {kz:"бақылау",en:"control",ru:"контроль",pos:"noun"},
  {kz:"тексеру",en:"verification",ru:"проверка",pos:"noun"},
  {kz:"растау",en:"confirmation",ru:"подтверждение",pos:"noun"},
  {kz:"бекіту",en:"approval",ru:"утверждение",pos:"noun"},
  {kz:"қабылдау",en:"acceptance",ru:"принятие",pos:"noun"},
  {kz:"қабылдану",en:"to be accepted",ru:"быть принятым",pos:"verb"},
  {kz:"бас тарту",en:"refusal",ru:"отказ",pos:"noun"},
  {kz:"бас тарту",en:"to refuse",ru:"отказываться",pos:"verb"},
  {kz:"келісу",en:"to agree",ru:"соглашаться",pos:"verb"},
  {kz:"келісім",en:"agreement",ru:"соглашение",pos:"noun"},
  {kz:"келісімшарт",en:"contract",ru:"контракт",pos:"noun"},
  {kz:"шарт",en:"condition",ru:"условие",pos:"noun"},
  {kz:"уағдаласу",en:"to negotiate",ru:"договариваться",pos:"verb"},
  {kz:"мәміле",en:"deal",ru:"сделка",pos:"noun"},
  {kz:"мәмілелесу",en:"to make a deal",ru:"заключать сделку",pos:"verb"},
  {kz:"сауда",en:"trade",ru:"торговля",pos:"noun"},
  {kz:"экспорт",en:"export",ru:"экспорт",pos:"noun"},
  {kz:"импорт",en:"import",ru:"импорт",pos:"noun"},
  {kz:"логистика",en:"logistics",ru:"логистика",pos:"noun"},
  {kz:"тасымалдау",en:"transportation",ru:"перевозка",pos:"noun"},
  {kz:"жөнелту",en:"dispatch",ru:"отправка",pos:"noun"},
  {kz:"қабылдау",en:"reception",ru:"приёмка",pos:"noun"},
  {kz:"сапа",en:"quality",ru:"качество",pos:"noun"},
  {kz:"сан",en:"quantity",ru:"количество",pos:"noun"},
  {kz:"баға",en:"price",ru:"цена",pos:"noun"},
  {kz:"баға белгілеу",en:"pricing",ru:"ценообразование",pos:"noun"},
  {kz:"жеңілдік",en:"discount",ru:"скидка",pos:"noun"},
  {kz:"жеңілдік жасау",en:"to give discount",ru:"делать скидку",pos:"verb"},
  {kz:"сату",en:"sale",ru:"продажа",pos:"noun"},
  {kz:"сатып алу",en:"purchase",ru:"покупка",pos:"noun"},
  {kz:"төлеу",en:"payment",ru:"оплата",pos:"noun"},
  {kz:"төлем",en:"payment",ru:"платёж",pos:"noun"},
  {kz:"несие",en:"credit",ru:"кредит",pos:"noun"},
  {kz:"несиелендіру",en:"financing",ru:"кредитование",pos:"noun"},
  {kz:"инвестиция",en:"investment",ru:"инвестиция",pos:"noun"},
  {kz:"инвестициялау",en:"investing",ru:"инвестирование",pos:"verb"},
  {kz:"қор",en:"fund",ru:"фонд",pos:"noun"},
  {kz:"бюджет",en:"budget",ru:"бюджет",pos:"noun"},
  {kz:"экономика",en:"economy",ru:"экономика",pos:"noun"},
  {kz:"нарық",en:"market",ru:"рынок",pos:"noun"},
  {kz:"сұраныс",en:"demand",ru:"спрос",pos:"noun"},
  {kz:"ұсыныс",en:"supply",ru:"предложение",pos:"noun"},
  {kz:"инфляция",en:"inflation",ru:"инфляция",pos:"noun"},
  {kz:"дефляция",en:"deflation",ru:"дефляция",pos:"noun"},
  {kz:"рецессия",en:"recession",ru:"рецессия",pos:"noun"},
  {kz:"өсу",en:"growth",ru:"рост",pos:"noun"},
  {kz:"құлдырау",en:"decline",ru:"спад",pos:"noun"},
  {kz:"дағдарыс",en:"crisis",ru:"кризис",pos:"noun"},
  {kz:"тұрақтылық",en:"stability",ru:"стабильность",pos:"noun"},
  {kz:"тəуекел",en:"risk",ru:"риск",pos:"noun"},
  {kz:"сақтандыру",en:"insurance",ru:"страхование",pos:"noun"},
  {kz:"сақтандыру полисі",en:"insurance policy",ru:"страховой полис",pos:"noun"},
  {kz:"компенсация",en:"compensation",ru:"компенсация",pos:"noun"},
  {kz:"өтемі",en:"compensation",ru:"возмещение",pos:"noun"},
  {kz:"кәсіп",en:"profession",ru:"профессия",pos:"noun"},
  {kz:"мамандық",en:"specialty",ru:"специальность",pos:"noun"},
  {kz:"дағды",en:"skill",ru:"навык",pos:"noun"},
  {kz:"шеберлік",en:"mastery",ru:"мастерство",pos:"noun"},
  {kz:"тəжірибе",en:"experience",ru:"опыт",pos:"noun"},
  {kz:"біліктілік",en:"qualification",ru:"квалификация",pos:"noun"},
  {kz:"дәреже",en:"degree",ru:"степень",pos:"noun"},
  {kz:"ранг",en:"rank",ru:"ранг",pos:"noun"},
  {kz:"лауазым",en:"position",ru:"должность",pos:"noun"},
  {kz:"атақ",en:"title",ru:"звание",pos:"noun"},
  {kz:"марапат",en:"award",ru:"награда",pos:"noun"},
  {kz:"сыйлық",en:"prize",ru:"приз",pos:"noun"},
  {kz:"жүлде",en:"medal",ru:"медаль",pos:"noun"},
  {kz:"жүлдегер",en:"prize-winner",ru:"призёр",pos:"noun"},
  {kz:"чемпион",en:"champion",ru:"чемпион",pos:"noun"},
  {kz:"жолдама",en:"reference (letter)",ru:"рекомендательное письмо",pos:"noun"},
  {kz:"түсініктеме",en:"explanation",ru:"объяснение",pos:"noun"},
  {kz:"сипаттама",en:"description",ru:"описание",pos:"noun"},
  {kz:"шолу",en:"review",ru:"обзор",pos:"noun"},
  {kz:"бағалау",en:"assessment",ru:"оценка",pos:"noun"},
  {kz:"баға",en:"grade",ru:"оценка",pos:"noun"},
  {kz:"тест",en:"test",ru:"тест",pos:"noun"},
  {kz:"емтихан",en:"exam",ru:"экзамен",pos:"noun"},
  {kz:"сертификат",en:"certificate",ru:"сертификат",pos:"noun"},
  {kz:"лицензия",en:"license",ru:"лицензия",pos:"noun"},
  {kz:"патент",en:"patent",ru:"патент",pos:"noun"},
  {kz:"авторлық құқық",en:"copyright",ru:"авторское право",pos:"noun"},
  {kz:"тауар белгісі",en:"trademark",ru:"товарный знак",pos:"noun"},
  {kz:"логотип",en:"logo",ru:"логотип",pos:"noun"},
  {kz:"бренд",en:"brand",ru:"бренд",pos:"noun"},
  {kz:"марка",en:"brand (trade mark)",ru:"марка",pos:"noun"},
  {kz:"өнім",en:"product",ru:"продукт",pos:"noun"},
  {kz:"тауар",en:"goods",ru:"товар",pos:"noun"},
  {kz:"қызмет",en:"service",ru:"услуга",pos:"noun"},
  {kz:"əсер",en:"effect",ru:"эффект",pos:"noun"},
  {kz:"нəтиже",en:"result",ru:"результат",pos:"noun"},
  {kz:"шығу",en:"outcome",ru:"исход",pos:"noun"},
  {kz:"себеп",en:"cause",ru:"причина",pos:"noun"},
  {kz:"салдар",en:"consequence",ru:"последствие",pos:"noun"},
  {kz:"əсер ету",en:"to affect",ru:"воздействовать",pos:"verb"},
  {kz:"əсер еткіш",en:"agent",ru:"агент",pos:"noun"},
  {kz:"фактор",en:"factor",ru:"фактор",pos:"noun"},
  {kz:"шарт",en:"condition",ru:"условие",pos:"noun"},
  {kz:"жағдай",en:"situation",ru:"ситуация",pos:"noun"},
  {kz:"жай-күй",en:"state",ru:"состояние",pos:"noun"},
  {kz:"мəселе",en:"issue",ru:"вопрос",pos:"noun"},
  {kz:"мәселелік",en:"problematic",ru:"проблемный",pos:"adjective"},
  {kz:"шешім",en:"solution",ru:"решение",pos:"noun"},
  {kz:"шешуші",en:"decisive",ru:"решающий",pos:"adjective"},
  {kz:"қорытынды",en:"conclusion",ru:"заключение",pos:"noun"},
  {kz:"қорытындылау",en:"to conclude",ru:"заключать",pos:"verb"},
  {kz:"есеп беру",en:"reporting",ru:"отчётность",pos:"verb"},
  {kz:"есеп",en:"report",ru:"отчёт",pos:"noun"},
  {kz:"баланс",en:"balance",ru:"баланс",pos:"noun"},
  {kz:"statistika",en:"statistics",ru:"статистика",pos:"noun"},
  {kz:"график",en:"schedule",ru:"график",pos:"noun"},
  {kz:"кесте",en:"table",ru:"таблица",pos:"noun"},
  {kz:"диаграмма",en:"diagram",ru:"диаграмма",pos:"noun"},
  {kz:"карта",en:"map",ru:"карта",pos:"noun"},
  {kz:"схема",en:"scheme",ru:"схема",pos:"noun"},
  {kz:"жоба",en:"project",ru:"проект",pos:"noun"},
  {kz:"жоспарлау",en:"planning",ru:"планирование",pos:"noun"},
  {kz:"болжау",en:"forecasting",ru:"прогнозирование",pos:"noun"},
  {kz:"алдын алу",en:"prevention",ru:"профилактика",pos:"noun"},
  {kz:"алдын алу шаралары",en:"preventive measures",ru:"профилактические меры",pos:"noun"},
  {kz:"ескерту",en:"warning",ru:"предупреждение",pos:"noun"},
  {kz:"назарларды аудару",en:"awareness",ru:"информирование",pos:"noun"},
  {kz:"хроника",en:"chronicle",ru:"хроника",pos:"noun"},
  {kz:"журнал",en:"register",ru:"журнал",pos:"noun"},
  {kz:"кітап",en:"book",ru:"книга",pos:"noun"},
  {kz:"каталог",en:"catalog",ru:"каталог",pos:"noun"},
  {kz:"индекс",en:"index",ru:"индекс",pos:"noun"},
  {kz:"реестр",en:"register",ru:"реестр",pos:"noun"},
  {kz:"архив",en:"archive",ru:"архив",pos:"noun"},
  {kz:"құжат",en:"document",ru:"документ",pos:"noun"},
  {kz:"құжаттама",en:"documentation",ru:"документация",pos:"noun"},
  {kz:"растама",en:"certificate",ru:"свидетельство",pos:"noun"},
  {kz:"куəлік",en:"certificate",ru:"удостоверение",pos:"noun"},
  {kz:"рұқсат қағазы",en:"permit",ru:"разрешение",pos:"noun"},
  {kz:"лицензия",en:"license",ru:"лицензия",pos:"noun"},
  {kz:"келісім",en:"agreement",ru:"соглашение",pos:"noun"},
  {kz:"шарт",en:"treaty",ru:"договор",pos:"noun"},
  {kz:"конвенция",en:"convention",ru:"конвенция",pos:"noun"},
  {kz:"хаттама",en:"protocol",ru:"протокол",pos:"noun"},
  {kz:"меморандум",en:"memorandum",ru:"меморандум",pos:"noun"},
  {kz:"нота",en:"note",ru:"нота",pos:"noun"},
  {kz:"нотта",en:"note (diplomatic)",ru:"нота",pos:"noun"},
  {kz:"ультиматум",en:"ultimatum",ru:"ультиматум",pos:"noun"},
  {kz:"декларация",en:"declaration",ru:"декларация",pos:"noun"},
  {kz:"жарияланым",en:"publication",ru:"публикация",pos:"noun"},
  {kz:"жариялау",en:"publishing",ru:"публикация",pos:"verb"},
  {kz:"басып шығару",en:"printing",ru:"печать",pos:"verb"},
  {kz:"баспа",en:"publishing house",ru:"издательство",pos:"noun"},
  {kz:"редакция",en:"editorial office",ru:"редакция",pos:"noun"},
  {kz:"редактор",en:"editor",ru:"редактор",pos:"noun"},
  {kz:"корректор",en:"proofreader",ru:"корректор",pos:"noun"},
  {kz:"түзету",en:"correction",ru:"корректура",pos:"noun"},
  {kz:"транслитерация",en:"transliteration",ru:"транслитерация",pos:"noun"},
  {kz:"аударма",en:"translation",ru:"перевод",pos:"noun"},
  {kz:"аудару",en:"to translate",ru:"переводить",pos:"verb"},
  {kz:"толықтыру",en:"addition",ru:"дополнение",pos:"noun"},
  {kz:"толықтыру",en:"to supplement",ru:"дополнять",pos:"verb"},
  {kz:"қысқарту",en:"abbreviation",ru:"сокращение",pos:"noun"},
  {kz:"қысқарту",en:"to shorten",ru:"сокращать",pos:"verb"},
  {kz:"өзгерту",en:"modification",ru:"изменение",pos:"noun"},
  {kz:"өзгерту",en:"to modify",ru:"изменять",pos:"verb"},
  {kz:"жақсарту",en:"improvement",ru:"улучшение",pos:"noun"},
  {kz:"жақсарту",en:"to improve",ru:"улучшать",pos:"verb"},
  {kz:"нашарлату",en:"deterioration",ru:"ухудшение",pos:"noun"},
  {kz:"нашарлату",en:"to worsen",ru:"ухудшать",pos:"verb"},
  {kz:"күшейту",en:"strengthening",ru:"усиление",pos:"noun"},
  {kz:"күшейту",en:"to strengthen",ru:"усиливать",pos:"verb"},
  {kz:"əлсірету",en:"weakening",ru:"ослабление",pos:"noun"},
  {kz:"əлсірету",en:"to weaken",ru:"ослаблять",pos:"verb"},
  {kz:"дамыту",en:"development",ru:"развитие",pos:"noun"},
  {kz:"дамыту",en:"to develop",ru:"развивать",pos:"verb"},
  {kz:"тоқтату",en:"cessation",ru:"прекращение",pos:"noun"},
  {kz:"тоқтату",en:"to stop",ru:"останавливать",pos:"verb"},
  {kz:"жалғастыру",en:"continuation",ru:"продолжение",pos:"noun"},
  {kz:"жалғастыру",en:"to continue",ru:"продолжать",pos:"verb"},
  {kz:"бастау",en:"beginning",ru:"начало",pos:"noun"},
  {kz:"бастау",en:"to begin",ru:"начинать",pos:"verb"},
  {kz:"аяқтау",en:"completion",ru:"завершение",pos:"noun"},
  {kz:"аяқтау",en:"to complete",ru:"завершать",pos:"verb"},
  {kz:"қайталау",en:"repetition",ru:"повторение",pos:"noun"},
  {kz:"қайталау",en:"to repeat",ru:"повторять",pos:"verb"},
  {kz:"еске түсіру",en:"recollection",ru:"воспоминание",pos:"noun"},
  {kz:"еске түсіру",en:"to recall",ru:"вспоминать",pos:"verb"},
  {kz:"ұмыту",en:"forgetting",ru:"забывание",pos:"noun"},
  {kz:"ұмыту",en:"to forget",ru:"забывать",pos:"verb"},
  {kz:"білдіру",en:"expression",ru:"выражение",pos:"noun"},
  {kz:"білдіру",en:"to express",ru:"выражать",pos:"verb"},
  {kz:"көрсету",en:"demonstration",ru:"демонстрация",pos:"noun"},
  {kz:"көрсету",en:"to show",ru:"показывать",pos:"verb"},
  {kz:"жасыру",en:"hiding",ru:"сокрытие",pos:"noun"},
  {kz:"жасыру",en:"to hide",ru:"скрывать",pos:"verb"},
  {kz:"ашу",en:"opening",ru:"открытие",pos:"noun"},
  {kz:"ашу",en:"to open",ru:"открывать",pos:"verb"},
  {kz:"жабу",en:"closing",ru:"закрытие",pos:"noun"},
  {kz:"жабу",en:"to close",ru:"закрывать",pos:"verb"},
  {kz:"бекіту",en:"fixing",ru:"закрепление",pos:"noun"},
  {kz:"бекіту",en:"to fix",ru:"закреплять",pos:"verb"},
  {kz:"босату",en:"release",ru:"освобождение",pos:"noun"},
  {kz:"босату",en:"to release",ru:"освобождать",pos:"verb"},
  {kz:"байлау",en:"tying",ru:"связывание",pos:"noun"},
  {kz:"байлау",en:"to tie",ru:"связывать",pos:"verb"},
  {kz:"шешу",en:"solving",ru:"решение",pos:"noun"},
  {kz:"шешу",en:"to solve",ru:"решать",pos:"verb"},
  {kz:"құрастыру",en:"assembling",ru:"сборка",pos:"noun"},
  {kz:"құрастыру",en:"to assemble",ru:"собирать",pos:"verb"},
  {kz:"бөлшектеу",en:"disassembling",ru:"разборка",pos:"noun"},
  {kz:"бөлшектеу",en:"to disassemble",ru:"разбирать",pos:"verb"},
  {kz:"жөндеу",en:"repair",ru:"ремонт",pos:"noun"},
  {kz:"жөндеу",en:"to repair",ru:"ремонтировать",pos:"verb"},
  {kz:"бұзу",en:"breaking",ru:"ломание",pos:"noun"},
  {kz:"бұзу",en:"to break",ru:"ломать",pos:"verb"},
];
